module.exports={
    ADMIN_CREDENTIALS:'admin_credentials',
    ADD_CATEGORY:'add_category',
    ADD_BRAND:'add_brand',
    ADD_PRODUCT:'add_product',
    ADD_BANNER:'add_banner',
    USER_CREDENTIALS:'user_credentials',
    ADD_CART:'add_cart',
    ADD_WISHLIST:'add_wishlist',
    ORDER_COLLECTION:'order',
    COUPON_COLLECTION:'coupon'  
}